/**
 * Default UI Component Generator
 * 
 * Generates default UI component code for Dota2 custom games.
 */

import { WritePlanEntry } from "../../assembler/index.js";

/**
 * Generate default UI component code
 */
export function generateDefaultUIComponent(
  componentName: string,
  featureId: string
): string {
  return `import React from "react";

interface ${componentName}Props {
  data?: any;
}

/**
 * ${componentName}
 * 默认 UI 组件 - Generated by Rune Weaver
 */
export function ${componentName}(props: ${componentName}Props) {
  return (
    <Panel className="${componentName.toLowerCase()}-root">
      <Label text="${componentName}" />
    </Panel>
  );
}

export default ${componentName};
`;
}
