/**
 * Key Hint Component Generator
 * 
 * Generates UI key hint component code for Dota2 custom games.
 */

import { WritePlanEntry } from "../../assembler/index.js";

/**
 * Generate key hint component code
 */
export function generateKeyHintComponent(
  componentName: string,
  featureId: string
): string {
  return `import React, { useState, useEffect } from "react";

interface ${componentName}Props {
  keyText?: string;
  description?: string;
  showDescription?: boolean;
  isActive?: boolean;
}

/**
 * ${componentName}
 * 按键提示组件 - Generated by Rune Weaver
 */
export function ${componentName}(props: ${componentName}Props) {
  const { 
    keyText = "Q", 
    description = "冲刺技能", 
    showDescription = true,
    isActive = true 
  } = props;

  const [isPressed, setIsPressed] = useState(false);

  useEffect(() => {
    // 监听按键事件
    const onKeyPressed = () => setIsPressed(true);
    const onKeyReleased = () => setIsPressed(false);
    
    // TODO: 绑定到实际的按键事件
    
    return () => {
      // 清理事件监听
    };
  }, []);

  return (
    <Panel className={\`${componentName.toLowerCase()}-root \${isActive ? "active" : "inactive"} \${isPressed ? "pressed" : ""}\`}>
      <Panel className="key-icon">
        <Label text={keyText} />
      </Panel>
      {showDescription && (
        <Label className="key-description" text={description} />
      )}
    </Panel>
  );
}

export default ${componentName};
`;
}
