/**
 * Key Hint Component Generator
 * 
 * Generates UI key hint component code for Dota2 custom games.
 */

import { WritePlanEntry } from "../../assembler/index.js";

interface KeyHintParams {
  key?: string;
  text?: string;
  positionHint?: string;
}

function normalizeKey(value: unknown, fallback: string): string {
  return typeof value === "string" && value.trim().length > 0
    ? value.trim().toUpperCase()
    : fallback;
}

function normalizeText(value: unknown): string | undefined {
  return typeof value === "string" && value.trim().length > 0
    ? value.trim()
    : undefined;
}

function normalizePositionHint(value: unknown, fallback: string): string {
  return typeof value === "string" && value.trim().length > 0
    ? value.trim()
    : fallback;
}

/**
 * Generate key hint component code
 */
export function generateKeyHintComponent(
  componentName: string,
  featureId: string,
  entry: WritePlanEntry
): string {
  const params = (entry.parameters || {}) as KeyHintParams;
  const defaultKey = normalizeKey(params.key, "Q");
  const defaultText = normalizeText(params.text);
  const defaultPositionHint = normalizePositionHint(params.positionHint, "inline");
  const cssBaseName = entry.targetPath.split("/").pop()?.replace(".tsx", "").toLowerCase() || componentName.toLowerCase();

  return `import React from "react";

interface ${componentName}Props {
  keyText?: string;
  text?: string;
  positionHint?: string;
  visible?: boolean;
}

/**
 * ${componentName}
 * 按键提示组件 - Generated by Rune Weaver
 *
 * Current honest slice:
 * - static configured key + label display
 * - no runtime key-state or cooldown synchronization
 * - feature: "${featureId}"
 */
export function ${componentName}(props: ${componentName}Props) {
  const {
    keyText = ${JSON.stringify(defaultKey)},
    text = ${defaultText === undefined ? "undefined" : JSON.stringify(defaultText)},
    positionHint = ${JSON.stringify(defaultPositionHint)},
    visible = true,
  } = props;

  if (!visible) {
    return null;
  }

  const normalizedPositionHint = String(positionHint || "inline")
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "") || "inline";

  return (
    <Panel className={\`${cssBaseName}-root ${cssBaseName}-position-\${normalizedPositionHint}\`}>
      <Panel className="${cssBaseName}-key">
        <Label className="${cssBaseName}-key-label" text={keyText} />
      </Panel>
      {text ? <Label className="${cssBaseName}-text" text={text} /> : null}
    </Panel>
  );
}

export default ${componentName};
`;
}
