/**
 * LESS Styles Generator
 * 
 * Generates LESS stylesheet code for Dota2 custom games UI components.
 */

import { WritePlanEntry } from "../../assembler/index.js";

/**
 * Generate LESS styles code
 */
export function generateLessStyles(
  patternId: string,
  entry: WritePlanEntry,
  featureId: string
): string {
  const baseName = entry.targetPath.split("/").pop()?.replace(".less", "") || "component";

  if (patternId === "ui.selection_modal") {
    return generateSelectionModalStyles(baseName, featureId, patternId);
  }
  
  return `/* Generated by Rune Weaver */
/* ${featureId} - ${patternId} */

.${baseName.toLowerCase()}-root {
  // 基础样式
  width: 100%;
  height: fit-children;
  
  // TODO: 添加组件特定样式
}
`;
}

function generateSelectionModalStyles(
  baseName: string,
  featureId: string,
  patternId: string
): string {
  const classBase = baseName.toLowerCase();

  return `/* Generated by Rune Weaver */
/* ${featureId} - ${patternId} */

.${classBase}-overlay {
  width: 100%;
  height: 100%;
  horizontal-align: center;
  vertical-align: center;
  background-color: #00000099;
  z-index: 50;
}

.${classBase}-modal {
  width: 820px;
  min-height: 360px;
  horizontal-align: center;
  vertical-align: center;
  flow-children: down;
  padding: 24px;
  background-color: #101820ee;
  border: 2px solid #8fd0ff66;
  box-shadow: #000000aa 0px 0px 18px 0px;
}

.modal-header {
  width: 100%;
  flow-children: down;
  margin-bottom: 18px;
}

.modal-header Label {
  width: 100%;
  color: #f2fbff;
  font-size: 30px;
  font-weight: bold;
  text-align: center;
}

.modal-description {
  margin-top: 6px;
  color: #b9ced8;
  font-size: 18px;
  font-weight: normal;
}

.modal-content {
  width: 100%;
  flow-children: right;
  horizontal-align: center;
}

.selection-card {
  width: 240px;
  height: 180px;
  margin: 0px 8px;
  padding: 14px;
  flow-children: down;
  background-color: #17242dcc;
  border: 2px solid #6c8b9a66;
}

.selection-card:hover {
  brightness: 1.5;
}

.selection-card.selected {
  border: 2px solid #ffd76a;
  background-color: #223849ee;
}

.selection-card.disabled,
.selection-card.placeholder {
  saturation: 0.15;
  brightness: 0.45;
}

.card-name {
  width: 100%;
  color: #ffffff;
  font-size: 22px;
  font-weight: bold;
  text-align: center;
}

.card-description {
  width: 100%;
  margin-top: 10px;
  color: #c8d7de;
  font-size: 16px;
  text-align: center;
  white-space: normal;
}

.card-tier {
  horizontal-align: center;
  margin-top: 12px;
  padding: 2px 10px;
  color: #ffffff;
  font-size: 16px;
  font-weight: bold;
  background-color: #475569;
}

.tier-r {
  background-color: #4f8fba;
}

.tier-sr {
  background-color: #3aa66b;
}

.tier-ssr {
  background-color: #b06ad9;
}

.tier-ur {
  background-color: #d5a43c;
}

.modal-footer {
  width: 100%;
  margin-top: 20px;
  flow-children: right;
  horizontal-align: center;
}

.btn-confirm,
.btn-dismiss {
  min-width: 150px;
  height: 44px;
  margin: 0px 8px;
  padding: 8px 20px;
  background-color: #2f7fa3;
  border: 1px solid #9fdfff99;
}

.btn-confirm:hover,
.btn-dismiss:hover {
  brightness: 1.4;
}

.btn-confirm.disabled {
  saturation: 0.1;
  brightness: 0.45;
}

.btn-confirm Label,
.btn-dismiss Label {
  horizontal-align: center;
  vertical-align: center;
  color: #ffffff;
  font-size: 20px;
  font-weight: bold;
}
`;
}
