/**
 * LESS Styles Generator
 * 
 * Generates LESS stylesheet code for Dota2 custom games UI components.
 */

import { WritePlanEntry } from "../../assembler/index.js";

/**
 * Generate LESS styles code
 */
export function generateLessStyles(
  patternId: string,
  entry: WritePlanEntry,
  featureId: string
): string {
  const baseName = entry.targetPath.split("/").pop()?.replace(".less", "") || "component";

  if (patternId === "ui.selection_modal") {
    return generateSelectionModalStyles(baseName, featureId, patternId);
  }

  if (patternId === "ui.key_hint") {
    return generateKeyHintStyles(baseName, featureId, patternId);
  }

  if (patternId === "ui.resource_bar") {
    return generateResourceBarStyles(baseName, featureId, patternId);
  }
  
  return `/* Generated by Rune Weaver */
/* ${featureId} - ${patternId} */

.${baseName.toLowerCase()}-root {
  // 基础样式
  width: 100%;
  height: fit-children;
  
  // TODO: 添加组件特定样式
}
`;
}

function generateResourceBarStyles(
  baseName: string,
  featureId: string,
  patternId: string
): string {
  const classBase = baseName.toLowerCase();

  return `/* Generated by Rune Weaver */
/* ${featureId} - ${patternId} */

.${classBase}-root {
  flow-children: down;
  width: 260px;
  height: fit-children;
  padding: 8px 10px;
  background-color: #101820dd;
  border: 1px solid #8fd0ff33;
}

.${classBase}-label {
  margin-bottom: 6px;
  color: #dbeaf2;
  font-size: 18px;
  font-weight: bold;
}

.${classBase}-track {
  width: 100%;
  height: 18px;
  padding: 2px;
  background-color: #18262e;
  border: 1px solid #51708488;
}

.${classBase}-bar {
  width: 100%;
  height: 100%;
}

.${classBase}-text {
  margin-top: 6px;
  color: #f5fbff;
  font-size: 16px;
  text-align: right;
}

.${classBase}-variant-default {
  border-color: #8fd0ff33;
}

.${classBase}-variant-compact {
  width: 220px;
  padding: 6px 8px;
}
`;
}

function generateKeyHintStyles(
  baseName: string,
  featureId: string,
  patternId: string
): string {
  const classBase = baseName.toLowerCase();

  return `/* Generated by Rune Weaver */
/* ${featureId} - ${patternId} */

.${classBase}-root {
  flow-children: right;
  width: fit-children;
  height: fit-children;
  padding: 6px 10px;
  border-radius: 8px;
  background-color: #101820dd;
  border: 1px solid #8fd0ff44;
}

.${classBase}-key {
  min-width: 36px;
  height: 36px;
  margin-right: 8px;
  padding: 4px 8px;
  background-color: #1b2d38;
  border: 1px solid #9fdfff88;
  vertical-align: center;
}

.${classBase}-key-label {
  horizontal-align: center;
  vertical-align: center;
  color: #f5fbff;
  font-size: 20px;
  font-weight: bold;
  text-align: center;
}

.${classBase}-text {
  vertical-align: center;
  color: #d3e4ed;
  font-size: 18px;
}

.${classBase}-position-inline {
  horizontal-align: left;
}

.${classBase}-position-top-right {
  horizontal-align: right;
  vertical-align: top;
}

.${classBase}-position-bottom-center {
  horizontal-align: center;
  vertical-align: bottom;
}
`;
}

function generateSelectionModalStyles(
  baseName: string,
  featureId: string,
  patternId: string
): string {
  const classBase = baseName.toLowerCase();

  return `/* Generated by Rune Weaver */
/* ${featureId} - ${patternId} */

.${classBase}-root {
  width: 100%;
  height: 100%;
}

.${classBase}-inventory-panel {
  width: 386px;
  min-height: 260px;
  horizontal-align: right;
  vertical-align: center;
  margin-right: 36px;
  flow-children: down;
  padding: 16px;
  background-color: #0d1720ee;
  border: 1px solid #8fd0ff33;
  box-shadow: #00000088 0px 0px 16px 0px;
  z-index: 40;
}

.inventory-header {
  width: 100%;
  flow-children: down;
  margin-bottom: 12px;
}

.inventory-title {
  color: #f5fbff;
  font-size: 24px;
  font-weight: bold;
}

.inventory-title.full {
  color: #ffd76a;
}

.inventory-subtitle {
  margin-top: 4px;
  color: #a9bcc7;
  font-size: 16px;
}

.inventory-grid {
  width: 100%;
  flow-children: right-wrap;
}

.inventory-slot {
  width: 64px;
  height: 64px;
  margin: 4px;
  padding: 6px;
  flow-children: down;
  border: 1px solid #6c8b9a66;
}

.inventory-slot.empty {
  background-color: #141f28cc;
}

.inventory-slot.filled {
  background-color: #1c2a36ee;
  border-color: #8fd0ff55;
}

.inventory-slot-name {
  width: 100%;
  color: #f5fbff;
  font-size: 12px;
  font-weight: semi-bold;
  text-align: center;
  white-space: normal;
}

.inventory-slot-tier {
  width: 100%;
  margin-top: 2px;
  color: #d7e5ec;
  font-size: 11px;
  text-align: center;
}

.inventory-slot-placeholder {
  width: 100%;
  vertical-align: center;
  color: #6f8592;
  font-size: 12px;
  text-align: center;
}

.${classBase}-overlay {
  width: 100%;
  height: 100%;
  horizontal-align: center;
  vertical-align: center;
  background-color: #00000099;
  z-index: 50;
}

.${classBase}-modal {
  width: 880px;
  min-height: 360px;
  horizontal-align: center;
  vertical-align: center;
  flow-children: down;
  padding: 24px;
  background-color: #101820ee;
  border: 2px solid #8fd0ff66;
  box-shadow: #000000aa 0px 0px 18px 0px;
}

.modal-header {
  width: 100%;
  flow-children: down;
  margin-bottom: 18px;
}

.modal-header Label {
  width: 100%;
  color: #f2fbff;
  font-size: 30px;
  font-weight: bold;
  text-align: center;
}

.modal-description {
  margin-top: 6px;
  color: #b9ced8;
  font-size: 18px;
  font-weight: normal;
}

.modal-content {
  width: 100%;
  flow-children: down;
}

.modal-options {
  width: 100%;
  flow-children: down;
}

.modal-options-row {
  width: fit-children;
  flow-children: right;
  horizontal-align: center;
  margin-bottom: 16px;
}

.selection-card {
  width: 240px;
  height: 180px;
  margin: 0px 8px;
  padding: 14px;
  flow-children: down;
  background-color: #17242dcc;
  border: 2px solid #6c8b9a66;
}

.selection-card:hover {
  brightness: 1.5;
}

.selection-card.selected {
  border: 2px solid #ffd76a;
  background-color: #223849ee;
}

.selection-card.disabled,
.selection-card.placeholder {
  saturation: 0.15;
  brightness: 0.45;
}

.card-name {
  width: 100%;
  color: #ffffff;
  font-size: 22px;
  font-weight: bold;
  text-align: center;
}

.card-description {
  width: 100%;
  margin-top: 10px;
  color: #c8d7de;
  font-size: 16px;
  text-align: center;
  white-space: normal;
}

.card-tier {
  horizontal-align: center;
  margin-top: 12px;
  padding: 2px 10px;
  color: #ffffff;
  font-size: 16px;
  font-weight: bold;
  background-color: #475569;
}

.tier-r {
  background-color: #4f8fba;
}

.tier-sr {
  background-color: #3aa66b;
}

.tier-ssr {
  background-color: #b06ad9;
}

.tier-ur {
  background-color: #d5a43c;
}

.modal-footer {
  width: 100%;
  margin-top: 20px;
  flow-children: right;
  horizontal-align: center;
}

.btn-confirm,
.btn-dismiss {
  min-width: 150px;
  height: 44px;
  margin: 0px 8px;
  padding: 8px 20px;
  background-color: #2f7fa3;
  border: 1px solid #9fdfff99;
}

.btn-confirm:hover,
.btn-dismiss:hover {
  brightness: 1.4;
}

.btn-confirm.disabled {
  saturation: 0.1;
  brightness: 0.45;
}

.btn-confirm Label,
.btn-dismiss Label {
  horizontal-align: center;
  vertical-align: center;
  color: #ffffff;
  font-size: 20px;
  font-weight: bold;
}
`;
}
