/**
 * Resource Bar Component Generator
 * 
 * Generates UI resource bar component code for Dota2 custom games.
 */

import { WritePlanEntry } from "../../assembler/index.js";

/**
 * Generate resource bar component code
 */
export function generateResourceBarComponent(
  componentName: string,
  featureId: string
): string {
  return `import React, { useState, useEffect } from "react";

interface ${componentName}Props {
  currentValue?: number;
  maxValue?: number;
  label?: string;
  color?: string;
  showText?: boolean;
}

/**
 * ${componentName}
 * 资源条组件 - Generated by Rune Weaver
 */
export function ${componentName}(props: ${componentName}Props) {
  const {
    currentValue = 100,
    maxValue = 100,
    label = "Mana",
    color = "#3498db",
    showText = true,
  } = props;

  const [current, setCurrent] = useState(currentValue);
  const [max, setMax] = useState(maxValue);

  useEffect(() => {
    // 监听 NetTable 更新
    // TODO: 绑定到 CustomNetTables 或 XNetTable
    
    const checkResource = () => {
      // 示例：从 NetTable 读取值
      // const data = CustomNetTables.GetTableValue("rune_weaver_resources", "player_0");
      // if (data) {
      //   setCurrent(data.current);
      //   setMax(data.max);
      // }
    };

    const intervalId = setInterval(checkResource, 100);
    
    return () => {
      clearInterval(intervalId);
    };
  }, []);

  const percentage = max > 0 ? (current / max) * 100 : 0;

  return (
    <Panel className="${componentName.toLowerCase()}-root">
      {label && <Label className="resource-label" text={label} />}
      <ProgressBar
        className="resource-bar"
        value={percentage}
        min={0}
        max={100}
        style={{ backgroundColor: color }}
      />
      {showText && (
        <Label
          className="resource-text"
          text={\`\${Math.floor(current)} / \${max}\`}
        />
      )}
    </Panel>
  );
}

export default ${componentName};
`;
}
