/**
 * Resource Bar Component Generator
 * 
 * Generates UI resource bar component code for Dota2 custom games.
 */

import { WritePlanEntry } from "../../assembler/index.js";

interface ResourceBarParams {
  resourceId?: string;
  displayName?: string;
  stylePreset?: string;
}

function normalizeLabel(value: unknown, fallback: string): string {
  return typeof value === "string" && value.trim().length > 0
    ? value.trim()
    : fallback;
}

function normalizeStylePreset(value: unknown, fallback: string): string {
  return typeof value === "string" && value.trim().length > 0
    ? value.trim()
    : fallback;
}

/**
 * Generate resource bar component code
 */
export function generateResourceBarComponent(
  componentName: string,
  featureId: string,
  entry: WritePlanEntry
): string {
  const params = (entry.parameters || {}) as ResourceBarParams;
  const defaultLabel = normalizeLabel(params.displayName ?? params.resourceId, "Resource");
  const defaultStylePreset = normalizeStylePreset(params.stylePreset, "default");
  const cssBaseName = entry.targetPath.split("/").pop()?.replace(".tsx", "").toLowerCase() || componentName.toLowerCase();

  return `import React from "react";

interface ${componentName}Props {
  currentValue?: number;
  maxValue?: number;
  label?: string;
  color?: string;
  showText?: boolean;
  stylePreset?: string;
}

/**
 * ${componentName}
 * 资源条组件 - Generated by Rune Weaver
 *
 * Current honest slice:
 * - static configured bar + text display
 * - no runtime resource polling or net-table synchronization
 * - feature: "${featureId}"
 */
export function ${componentName}(props: ${componentName}Props) {
  const {
    currentValue = 100,
    maxValue = 100,
    label = ${JSON.stringify(defaultLabel)},
    color = "#3498db",
    showText = true,
    stylePreset = ${JSON.stringify(defaultStylePreset)},
  } = props;

  const safeMax = Math.max(maxValue, 0);
  const clampedCurrent = Math.max(0, Math.min(currentValue, safeMax || currentValue));
  const percentage = safeMax > 0 ? (clampedCurrent / safeMax) * 100 : 0;
  const normalizedStylePreset = String(stylePreset || "default")
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "") || "default";

  return (
    <Panel className={\`${cssBaseName}-root ${cssBaseName}-variant-\${normalizedStylePreset}\`}>
      {label ? <Label className="${cssBaseName}-label" text={label} /> : null}
      <Panel className="${cssBaseName}-track">
        <ProgressBar
          className="${cssBaseName}-bar"
          value={percentage}
          min={0}
          max={100}
          style={{ backgroundColor: color }}
        />
      </Panel>
      {showText && (
        <Label
          className="${cssBaseName}-text"
          text={\`\${Math.floor(clampedCurrent)} / \${safeMax}\`}
        />
      )}
    </Panel>
  );
}

export default ${componentName};
`;
}
