/**
 * Dash Effect Generator
 * 
 * Generates server-side dash effect ability code for Dota2 custom games.
 */

import { WritePlanEntry } from "../../assembler/index.js";

/**
 * Generate dash effect code
 */
export function generateDashEffectCode(
  className: string,
  featureId: string,
  entry: WritePlanEntry
): string {
  return `import { BaseAbility } from "../../../utils/dota_ts_adapter";

/**
 * ${className}
 * 冲刺效果 - Generated by Rune Weaver
 */

export class ${className} extends BaseAbility {
  private readonly DEFAULT_DISTANCE: number = 300;
  private readonly DEFAULT_SPEED: number = 1200;

  /**
   * 执行冲刺
   */
  executeDash(): void {
    const caster = this.GetCaster();
    if (!caster || !IsServer()) return;

    const direction = caster.GetForwardVector();
    const distance = this.GetSpecialValueFor("distance") || this.DEFAULT_DISTANCE;
    const speed = this.GetSpecialValueFor("speed") || this.DEFAULT_SPEED;

    // 计算目标位置
    const startPos = caster.GetAbsOrigin();
    const endPos = startPos.__add(direction.__mul(distance)) as Vector;

    // 执行位移
    caster.AddNewModifier(
      caster,
      this,
      "modifier_${className.toLowerCase()}_motion",
      {
        duration: distance / speed,
        x: endPos.x,
        y: endPos.y,
        z: endPos.z,
      }
    );

    // 播放特效
    const particleId = ParticleManager.CreateParticle(
      "particles/units/heroes/hero_phantom_assassin/phantom_assassin_phantom_strike_start.vpcf",
      ParticleAttachment.ABSORIGIN_FOLLOW,
      caster
    );
    ParticleManager.ReleaseParticleIndex(particleId);

    // 播放音效
    caster.EmitSound("Hero_PhantomAssassin.PhantomStrike");
  }

  /**
   * 施法时调用
   */
  OnSpellStart(): void {
    this.executeDash();
  }
}

/**
 * 注册函数 - 由 Bridge 调用
 */
export function register${className}(): void {
  print("[Rune Weaver] ${className} registered");
}
`;
}
