/**
 * Default Server Generator
 * 
 * Generates default server-side module code for Dota2 custom games.
 */

import { WritePlanEntry } from "../../assembler/index.js";

/**
 * Generate default server code
 */
export function generateDefaultServerCode(
  className: string,
  featureId: string,
  entry: WritePlanEntry
): string {
  return `/**
 * ${className}
 * 默认模块 - Generated by Rune Weaver
 */

export class ${className} {
  private static instance: ${className};

  static getInstance(): ${className} {
    if (!${className}.instance) {
      ${className}.instance = new ${className}();
    }
    return ${className}.instance;
  }

  /**
   * 初始化
   */
  init(): void {
    print("[Rune Weaver] ${className} initialized");
  }
}

/**
 * 注册函数 - 由 Bridge 调用
 */
export function register${className}(): void {
  const instance = ${className}.getInstance();
  instance.init();
  print("[Rune Weaver] ${className} registered");
}
`;
}
