/**
 * Key Binding Generator
 *
 * Generates server-side key binding code for Dota2 custom games.
 */

import { WritePlanEntry } from "../../assembler/index.js";

interface KeyBindingParams {
  triggerKey?: string;
}

/**
 * Generate key binding code
 */
export function generateKeyBindingCode(
  className: string,
  featureId: string,
  entry: WritePlanEntry
): string {
  const params = (entry.parameters || {}) as KeyBindingParams;
  const triggerKey = params.triggerKey || "F4";

  return `/**
 * ${className}
 * 按键绑定模块 - Generated by Rune Weaver
 */

export class ${className} {
  private static instance: ${className};
  private boundKeys: Set<string> = new Set();
  private handler?: (playerId: number, event?: { [key: string]: unknown }) => void;
  private readonly configuredKey: string = "${triggerKey}";
  private readonly featureId: string = "${featureId}";
  private configuredKeyBound = false;

  static getInstance(): ${className} {
    if (!${className}.instance) {
      ${className}.instance = new ${className}();
    }
    return ${className}.instance;
  }

  /**
   * 绑定按键
   */
  bindKey(
    key: string,
    callback: (playerId: number, event?: { [key: string]: unknown }) => void
  ): void {
    if (this.boundKeys.has(key)) {
      print(\`[Rune Weaver] Key \${key} already bound, skipping\`);
      return;
    }

    this.boundKeys.add(key);

    if (GameRules && (GameRules as any).XNetTable) {
      CustomGameEventManager.RegisterListener("player_key_pressed", (_eventSourceIndex: number, event: any) => {
        if (!event || event.key !== key) {
          return;
        }

        if (event.featureId && event.featureId !== this.featureId) {
          return;
        }

        const playerId = Number(event.PlayerID ?? event.playerId ?? -1);
        if (playerId < 0) {
          print(\`[Rune Weaver] Ignored key \${key} because player id is missing\`);
          return;
        }

        callback(playerId, event);
      });
    }

    print(\`[Rune Weaver] Bound key: \${key} for feature \${this.featureId}\`);
  }

  /**
   * 解绑按键
   */
  unbindKey(key: string): void {
    this.boundKeys.delete(key);
    print(\`[Rune Weaver] Unbound key: \${key}\`);
  }

  setHandler(handler: (playerId: number, event?: { [key: string]: unknown }) => void): void {
    this.handler = handler;
    if (!this.configuredKeyBound) {
      this.bindConfiguredKey();
    }
  }

  bindConfiguredKey(): void {
    if (this.configuredKeyBound) {
      return;
    }
    this.configuredKeyBound = true;
    this.bindKey(this.configuredKey, (playerId, event) => {
      if (!this.handler) {
        print(\`[Rune Weaver] No handler configured for \${this.configuredKey} (\${this.featureId})\`);
        return;
      }
      this.handler(playerId, event);
    });
  }

  getConfiguredKey(): string {
    return this.configuredKey;
  }
}

/**
 * 注册函数 - 由 Bridge 调用
 */
export function register${className}(): void {
  ${className}.getInstance();
  print("[Rune Weaver] ${className} registered");
}
`;
}
