/**
 * Key Binding Generator
 *
 * Generates server-side key binding code for Dota2 custom games.
 */

import { WritePlanEntry } from "../../assembler/index.js";

interface KeyBindingParams {
  triggerKey?: string;
  key?: string;
  eventName?: string;
}

interface KeyBindingInvocationMetadata {
  resourceInvocationImportPath?: string;
  resourceInvocationTargetPath?: string;
  resourceInvocationClassName?: string;
  resourceInvocationMode?: string;
  resourceInvocationResourceType?: string;
}

/**
 * Generate key binding code
 */
export function generateKeyBindingCode(
  className: string,
  featureId: string,
  entry: WritePlanEntry
): string {
  const params = (entry.parameters || {}) as KeyBindingParams;
  const metadata = (entry.metadata || {}) as KeyBindingInvocationMetadata;
  const triggerKey = typeof (params.triggerKey || params.key) === "string"
    ? String(params.triggerKey || params.key).trim().toUpperCase()
    : "";
  if (!triggerKey) {
    throw new Error("input.key_binding requires an explicit triggerKey/key parameter.");
  }
  const eventName =
    typeof params.eventName === "string" && params.eventName.trim().length > 0
      ? params.eventName.trim()
      : "rune_weaver_input_triggered";
  const hasResourceInvocation =
    metadata.resourceInvocationMode === "resource-consume-configured" &&
    typeof metadata.resourceInvocationImportPath === "string" &&
    metadata.resourceInvocationImportPath.length > 0 &&
    typeof metadata.resourceInvocationClassName === "string" &&
    metadata.resourceInvocationClassName.length > 0;
  const importBlock = hasResourceInvocation
    ? `import { ${metadata.resourceInvocationClassName} } from "${metadata.resourceInvocationImportPath}";\n\n`
    : "";
  const invocationComment = hasResourceInvocation
    ? ` * Canonical invocation:\n * - same-feature input.key_binding -> effect.resource_consume (${metadata.resourceInvocationResourceType || "mana"})\n`
    : "";
  const registerBlock = hasResourceInvocation
    ? `  const keyBinding = ${className}.getInstance();
  const resourceConsumer = ${metadata.resourceInvocationClassName}.getInstance();
  keyBinding.setHandler((playerId: number) => {
    const result = resourceConsumer.consumeConfiguredAmount(playerId);
    if (!result.success) {
      print(
        \`[Rune Weaver] ${className}: resource consume invocation failed (\${result.reason || "unknown"}) for \${result.resourceType}\`
      );
    }
  });
`
    : `  ${className}.getInstance();
`;
  const registerNote = hasResourceInvocation
    ? `"[Rune Weaver] ${className} registered with canonical resource consume caller"`
    : `"[Rune Weaver] ${className} registered"`;

  return `${importBlock}/**
 * ${className}
 * 按键绑定模块 - Generated by Rune Weaver
${invocationComment} */

export class ${className} {
  private static instance: ${className};
  private boundKeys: Set<string> = new Set();
  private handler?: (playerId: number, event?: { [key: string]: unknown }) => void;
  private readonly configuredKey: string = "${triggerKey}";
  private readonly eventName: string = "${eventName}";
  private readonly featureId: string = "${featureId}";
  private configuredKeyBound = false;

  static getInstance(): ${className} {
    if (!${className}.instance) {
      ${className}.instance = new ${className}();
    }
    return ${className}.instance;
  }

  /**
   * 绑定按键
   */
  bindKey(
    key: string,
    callback: (playerId: number, event?: { [key: string]: unknown }) => void
  ): void {
    if (this.boundKeys.has(key)) {
      print(\`[Rune Weaver] Key \${key} already bound, skipping\`);
      return;
    }

    this.boundKeys.add(key);

    if (GameRules && (GameRules as any).XNetTable) {
      CustomGameEventManager.RegisterListener(this.eventName, (_eventSourceIndex: number, event: any) => {
        if (!event || event.key !== key) {
          return;
        }

        if (event.featureId && event.featureId !== this.featureId) {
          return;
        }

        const playerId = Number(event.PlayerID ?? event.playerId ?? -1);
        if (playerId < 0) {
          print(\`[Rune Weaver] Ignored key \${key} because player id is missing\`);
          return;
        }

        callback(playerId, event);
      });
    }

    print(\`[Rune Weaver] Bound key: \${key} for feature \${this.featureId} via \${this.eventName}\`);
  }

  /**
   * 解绑按键
   */
  unbindKey(key: string): void {
    this.boundKeys.delete(key);
    print(\`[Rune Weaver] Unbound key: \${key}\`);
  }

  setHandler(handler: (playerId: number, event?: { [key: string]: unknown }) => void): void {
    this.handler = handler;
    if (!this.configuredKeyBound) {
      this.bindConfiguredKey();
    }
  }

  bindConfiguredKey(): void {
    if (this.configuredKeyBound) {
      return;
    }
    this.configuredKeyBound = true;
    this.bindKey(this.configuredKey, (playerId, event) => {
      if (!this.handler) {
        print(\`[Rune Weaver] No handler configured for \${this.configuredKey} (\${this.featureId})\`);
        return;
      }
      this.handler(playerId, event);
    });
  }

  getConfiguredKey(): string {
    return this.configuredKey;
  }

  getEventName(): string {
    return this.eventName;
  }
}

/**
 * 注册函数 - 由 Bridge 调用
 */
export function register${className}(): void {
${registerBlock}  print(${registerNote});
}
`;
}
