/**
 * Selection Outcome Realizer Generator
 *
 * Owns:
 * - current-feature outcome lookup
 * - host-native attribute/item/unit realization
 * - registration onto selection_flow outcome handler seam
 *
 * Does not own:
 * - draw/select/confirm orchestration
 * - weighted pool session state
 * - cross-feature grants
 */

import { WritePlanEntry } from "../../assembler/index.js";

// Dota2 gap-fill boundary anchors.
// GAP_FILL_BOUNDARY: selection_outcome.realization
// GAP_FILL_BOUNDARY: selection_flow.effect_mapping
export const SELECTION_OUTCOME_GAP_FILL_BOUNDARIES = {
  realization: {
    id: "selection_outcome.realization",
    allowed: ["rarity_formula", "case_value_mapping", "option_to_effect_translation"],
    forbidden: ["event_channel_changes", "session_ownership_changes", "pattern_binding_changes"],
  },
  legacyEffectMappingAlias: {
    id: "selection_flow.effect_mapping",
    redirectedTo: "selection_outcome.realization",
  },
} as const;

interface AttributeBonusOutcomeSpec {
  kind: "attribute_bonus";
  attribute: "strength" | "agility" | "intelligence" | "all";
  value: number;
}

interface NativeItemDeliveryOutcomeSpec {
  kind: "native_item_delivery";
  itemName: string;
  deliveryMode: "hero_inventory" | "ground_drop";
  fallbackWhenInventoryFull: "drop_to_ground" | "skip_delivery";
  positionPolicy: "hero_origin" | "hero_forward" | "cursor_point";
}

interface SpawnUnitOutcomeSpec {
  kind: "spawn_unit";
  unitName: string;
  spawnCount?: number;
  positionPolicy: "hero_origin" | "hero_forward" | "cursor_point";
  teamScope?: "player_team";
}

type OutcomeSpec =
  | AttributeBonusOutcomeSpec
  | NativeItemDeliveryOutcomeSpec
  | SpawnUnitOutcomeSpec;

interface OutcomeRealizerParams {
  outcomes?: Array<{ id: string; outcome: OutcomeSpec }>;
}

function escapeLuaUnsafeString(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function buildOutcomeCode(outcome: OutcomeSpec): string {
  if (outcome.kind === "attribute_bonus") {
    return `{ kind: "attribute_bonus", attribute: "${outcome.attribute}", value: ${Number(outcome.value)} }`;
  }
  if (outcome.kind === "native_item_delivery") {
    return [
      "{",
      '  kind: "native_item_delivery",',
      `  itemName: "${escapeLuaUnsafeString(outcome.itemName)}",`,
      `  deliveryMode: "${outcome.deliveryMode}",`,
      `  fallbackWhenInventoryFull: "${outcome.fallbackWhenInventoryFull}",`,
      `  positionPolicy: "${outcome.positionPolicy}",`,
      "}",
    ].join("\n");
  }
  return [
    "{",
    '  kind: "spawn_unit",',
    `  unitName: "${escapeLuaUnsafeString(outcome.unitName)}",`,
    `  spawnCount: ${Math.max(1, Math.floor(Number(outcome.spawnCount || 1)))},`,
    `  positionPolicy: "${outcome.positionPolicy}",`,
    `  teamScope: "${outcome.teamScope || "player_team"}",`,
    "}",
  ].join("\n");
}

export function generateOutcomeRealizerCode(
  className: string,
  featureId: string,
  entry: WritePlanEntry
): string {
  const params = (entry.parameters || {}) as OutcomeRealizerParams;
  const outcomes = Array.isArray(params.outcomes) ? params.outcomes : [];
  const outcomesCode = outcomes.length > 0
    ? outcomes
        .map((record) => `    "${record.id}": ${buildOutcomeCode(record.outcome)}`)
        .join(",\n")
    : "";

  return `/**
 * ${className}
 * 选择结果宿主实现层 - Generated by Rune Weaver
 */

interface SelectionOption {
  id: string;
  name: string;
  description: string;
  icon?: string;
  tier?: string;
}

interface SelectionWorldPosition {
  x: number;
  y: number;
  z: number;
}

interface SelectionOutcomeRequest {
  featureId: string;
  playerId: number;
  option: SelectionOption;
  cursorPosition?: SelectionWorldPosition;
}

interface SelectionOutcomeHandlerResult {
  handled: boolean;
}

interface AttributeBonusOutcomeSpec {
  kind: "attribute_bonus";
  attribute: "strength" | "agility" | "intelligence" | "all";
  value: number;
}

interface NativeItemDeliveryOutcomeSpec {
  kind: "native_item_delivery";
  itemName: string;
  deliveryMode: "hero_inventory" | "ground_drop";
  fallbackWhenInventoryFull: "drop_to_ground" | "skip_delivery";
  positionPolicy: "hero_origin" | "hero_forward" | "cursor_point";
}

interface SpawnUnitOutcomeSpec {
  kind: "spawn_unit";
  unitName: string;
  spawnCount?: number;
  positionPolicy: "hero_origin" | "hero_forward" | "cursor_point";
  teamScope?: "player_team";
}

type OutcomeSpec =
  | AttributeBonusOutcomeSpec
  | NativeItemDeliveryOutcomeSpec
  | SpawnUnitOutcomeSpec;

type SelectionFlowLike = {
  registerOutcomeHandler: (
    handler: (context: SelectionOutcomeRequest & { request?: SelectionOutcomeRequest }) => SelectionOutcomeHandlerResult | void
  ) => void;
};

export class ${className} {
  private static instance: ${className};
  private attached = false;
  private outcomesById: Record<string, OutcomeSpec> = {
${outcomesCode}
  };

  static getInstance(): ${className} {
    if (!${className}.instance) {
      ${className}.instance = new ${className}();
    }
    return ${className}.instance;
  }

  attachToSelectionFlow(selectionFlow: SelectionFlowLike | undefined): void {
    if (!selectionFlow || typeof selectionFlow.registerOutcomeHandler !== "function" || this.attached) {
      return;
    }

    selectionFlow.registerOutcomeHandler((context) => {
      const request = context.request || context;
      const handled = this.handleOutcomeRequest(request);
      return { handled };
    });
    this.attached = true;
    print("[Rune Weaver] ${className}: attached to selection flow for feature ${featureId}");
  }

  private handleOutcomeRequest(request: SelectionOutcomeRequest): boolean {
    const outcome = this.outcomesById[request.option.id];
    if (!outcome) {
      return false;
    }

    switch (outcome.kind) {
      case "attribute_bonus":
        this.realizeAttributeBonus(request, outcome);
        return true;
      case "native_item_delivery":
        this.realizeNativeItemDelivery(request, outcome);
        return true;
      case "spawn_unit":
        this.realizeSpawnUnit(request, outcome);
        return true;
      default:
        print(\`[Rune Weaver] ${className}: unknown outcome kind for \${request.option.id}\`);
        return true;
    }
  }

  private resolveHero(playerId: number): CDOTA_BaseNPC_Hero | undefined {
    const hero = PlayerResource.GetSelectedHeroEntity(playerId as PlayerID);
    if (!hero) {
      print(\`[Rune Weaver] ${className}: no hero found for player \${playerId}\`);
      return undefined;
    }
    return hero;
  }

  private resolveItemOwner(playerId: number): CDOTAPlayerController | undefined {
    return PlayerResource.GetPlayer(playerId as PlayerID);
  }

  private emitAttributeBonusEvent(
    request: SelectionOutcomeRequest,
    outcome: AttributeBonusOutcomeSpec,
  ): void {
    const player = PlayerResource.GetPlayer(request.playerId as PlayerID);
    if (!player || !CustomGameEventManager) {
      return;
    }

    (CustomGameEventManager.Send_ServerToPlayer as any)(
      player,
      "rune_weaver_effect_applied",
      {
        featureId: "${featureId}",
        optionId: request.option.id,
        optionName: request.option.name,
        attribute: outcome.attribute,
        value: outcome.value,
        rarity: request.option.tier || "R",
      }
    );
  }

  private realizeAttributeBonus(
    request: SelectionOutcomeRequest,
    outcome: AttributeBonusOutcomeSpec,
  ): void {
    const hero = this.resolveHero(request.playerId);
    if (!hero) {
      return;
    }

    switch (outcome.attribute) {
      case "strength":
        hero.ModifyStrength(outcome.value);
        break;
      case "agility":
        hero.ModifyAgility(outcome.value);
        break;
      case "intelligence":
        hero.ModifyIntellect(outcome.value);
        break;
      case "all":
        hero.ModifyStrength(outcome.value);
        hero.ModifyAgility(outcome.value);
        hero.ModifyIntellect(outcome.value);
        break;
      default:
        print(\`[Rune Weaver] ${className}: unknown attribute \${outcome.attribute}\`);
        return;
    }

    this.emitAttributeBonusEvent(request, outcome);
  }

  private resolveBoundedPosition(
    hero: CDOTA_BaseNPC_Hero,
    request: SelectionOutcomeRequest,
    positionPolicy: "hero_origin" | "hero_forward" | "cursor_point",
    index: number = 0,
  ): Vector {
    const origin = hero.GetAbsOrigin();
    const forward = hero.GetForwardVector();
    const lateralX = -forward.y;
    const lateralY = forward.x;
    const spreadCenter =
      index <= 0
        ? 0
        : (index % 2 === 0 ? 1 : -1) * Math.ceil(index / 2) * 96;

    if (positionPolicy === "cursor_point" && request.cursorPosition) {
      return Vector(
        request.cursorPosition.x + lateralX * spreadCenter,
        request.cursorPosition.y + lateralY * spreadCenter,
        request.cursorPosition.z,
      );
    }

    if (positionPolicy === "hero_forward") {
      return Vector(
        origin.x + forward.x * 160 + lateralX * spreadCenter,
        origin.y + forward.y * 160 + lateralY * spreadCenter,
        origin.z,
      );
    }

    return Vector(
      origin.x + lateralX * spreadCenter,
      origin.y + lateralY * spreadCenter,
      origin.z,
    );
  }

  private hasAvailableInventorySlot(hero: CDOTA_BaseNPC_Hero): boolean {
    for (let slot = 0; slot < 6; slot += 1) {
      if (!hero.GetItemInSlot(slot)) {
        return true;
      }
    }
    return false;
  }

  private dropItemAtPosition(
    owner: CDOTAPlayerController | undefined,
    hero: CDOTA_BaseNPC_Hero,
    itemName: string,
    position: Vector,
  ): void {
    const item = CreateItem(itemName, owner, hero);
    if (!item) {
      print(\`[Rune Weaver] ${className}: failed to create item \${itemName}\`);
      return;
    }
    CreateItemOnPositionSync(position, item);
  }

  private realizeNativeItemDelivery(
    request: SelectionOutcomeRequest,
    outcome: NativeItemDeliveryOutcomeSpec,
  ): void {
    const hero = this.resolveHero(request.playerId);
    const owner = this.resolveItemOwner(request.playerId);
    if (!hero) {
      return;
    }

    if (outcome.deliveryMode === "ground_drop") {
      this.dropItemAtPosition(owner, hero, outcome.itemName, this.resolveBoundedPosition(hero, request, outcome.positionPolicy));
      return;
    }

    if (this.hasAvailableInventorySlot(hero)) {
      const item = CreateItem(outcome.itemName, owner, hero);
      if (!item) {
        print(\`[Rune Weaver] ${className}: failed to create item \${outcome.itemName}\`);
        return;
      }
      hero.AddItem(item);
      return;
    }

    if (outcome.fallbackWhenInventoryFull === "drop_to_ground") {
      this.dropItemAtPosition(owner, hero, outcome.itemName, this.resolveBoundedPosition(hero, request, outcome.positionPolicy));
      return;
    }

    print(\`[Rune Weaver] ${className}: inventory full, skipped item delivery for \${outcome.itemName}\`);
  }

  private realizeSpawnUnit(
    request: SelectionOutcomeRequest,
    outcome: SpawnUnitOutcomeSpec,
  ): void {
    const hero = this.resolveHero(request.playerId);
    if (!hero) {
      return;
    }

    const teamNumber = hero.GetTeamNumber();
    const spawnCount = Math.max(1, Math.floor(outcome.spawnCount || 1));
    for (let index = 0; index < spawnCount; index += 1) {
      CreateUnitByName(
        outcome.unitName,
        this.resolveBoundedPosition(hero, request, outcome.positionPolicy, index),
        true,
        hero,
        hero,
        teamNumber,
      );
    }
  }
}

export function register${className}(): void {
  ${className}.getInstance();
  print("[Rune Weaver] ${className} registered");
}
`;
}
