/**
 * Resource Pool Generator
 * 
 * Generates server-side resource pool (cooldown/energy system) code for Dota2 custom games.
 */

import { WritePlanEntry } from "../../assembler/index.js";

/**
 * Generate resource pool code
 */
export function generateResourcePoolCode(
  className: string,
  featureId: string,
  entry: WritePlanEntry
): string {
  return `/**
 * ${className}
 * 资源池（冷却/能量系统）- Generated by Rune Weaver
 */

interface ResourceState {
  current: number;
  max: number;
  lastUsedTime: number;
}

export class ${className} {
  private static instance: ${className};
  private playerResources: Map<number, ResourceState> = new Map();
  private readonly defaultMax: number = 100;
  private readonly regenRate: number = 0;

  static getInstance(): ${className} {
    if (!${className}.instance) {
      ${className}.instance = new ${className}();
    }
    return ${className}.instance;
  }

  /**
   * 初始化玩家资源
   */
  initPlayer(playerId: number, maxValue?: number): void {
    this.playerResources.set(playerId, {
      current: maxValue || this.defaultMax,
      max: maxValue || this.defaultMax,
      lastUsedTime: 0,
    });
    print(\`[Rune Weaver] Initialized resource for player \${playerId}\`);
  }

  /**
   * 检查是否有足够资源
   */
  hasEnough(playerId: number, amount: number): boolean {
    const res = this.playerResources.get(playerId);
    if (!res) return false;
    return res.current >= amount;
  }

  /**
   * 消耗资源
   */
  consume(playerId: number, amount: number): boolean {
    if (!this.hasEnough(playerId, amount)) return false;
    
    const res = this.playerResources.get(playerId)!;
    res.current -= amount;
    res.lastUsedTime = GameRules.GetGameTime();
    
    this.syncToClient(playerId);
    return true;
  }

  /**
   * 恢复资源
   */
  restore(playerId: number, amount: number): void {
    const res = this.playerResources.get(playerId);
    if (!res) return;
    
    res.current = math.min(res.current + amount, res.max);
    this.syncToClient(playerId);
  }

  /**
   * 获取当前值
   */
  getCurrent(playerId: number): number {
    return this.playerResources.get(playerId)?.current || 0;
  }

  /**
   * 获取最大值
   */
  getMax(playerId: number): number {
    return this.playerResources.get(playerId)?.max || 0;
  }

  /**
   * 同步到客户端（通过 NetTable）
   */
  private syncToClient(playerId: number): void {
    const res = this.playerResources.get(playerId);
    if (!res) return;
    
    // 使用 XNetTable 同步（如果可用）
    if ((GameRules as any).XNetTable) {
      (GameRules as any).XNetTable.SetTableValue(
        "rune_weaver_resources",
        \`player_\${playerId}\`,
        { current: res.current, max: res.max }
      );
    }
  }

  /**
   * 每帧更新
   */
  onTick(): void {
    if (this.regenRate <= 0) return;
    
    const now = GameRules.GetGameTime();
    for (const [playerId, res] of this.playerResources) {
      if (res.current < res.max) {
        // 简单的自动恢复逻辑
        // 实际实现可能需要更复杂的计时器
      }
    }
  }
}

/**
 * 注册函数 - 由 Bridge 调用
 */
export function register${className}(): void {
  const pool = ${className}.getInstance();
  print("[Rune Weaver] ${className} registered");
  
  // 监听玩家连接事件 - 使用 GameRules 和自定义事件
  ListenToGameEvent("player_connect_full", (event: any) => {
    const playerId = event.PlayerID;
    if (playerId !== undefined) {
      pool.initPlayer(playerId);
    }
  }, undefined);
}
`;
}
