/**
 * Resource Pool Generator
 * 
 * Generates server-side resource pool (cooldown/energy system) code for Dota2 custom games.
 */

import { WritePlanEntry } from "../../assembler/index.js";

interface ResourcePoolParams {
  resourceId?: string;
  maxValue?: number | string;
  initial?: number | string;
  regen?: number | string;
}

function toPositiveNumber(value: unknown, fallback: number): number {
  if (typeof value === "number" && Number.isFinite(value) && value > 0) {
    return value;
  }

  if (typeof value === "string") {
    const parsed = Number(value);
    if (Number.isFinite(parsed) && parsed > 0) {
      return parsed;
    }
  }

  return fallback;
}

function toNonNegativeNumber(value: unknown, fallback: number): number {
  if (typeof value === "number" && Number.isFinite(value) && value >= 0) {
    return value;
  }

  if (typeof value === "string") {
    const parsed = Number(value);
    if (Number.isFinite(parsed) && parsed >= 0) {
      return parsed;
    }
  }

  return fallback;
}

function toResourceIdentifier(value: unknown, fallback: string): string {
  return typeof value === "string" && value.trim().length > 0 ? value.trim().toLowerCase() : fallback;
}

function parseSupportedRegen(value: unknown): number {
  const regenRate = toNonNegativeNumber(value, 0);
  if (regenRate > 0) {
    throw new Error(
      `resource.basic_pool only supports regen = 0 in the current resource/cost slice (received ${regenRate})`
    );
  }

  return regenRate;
}

/**
 * Generate resource pool code
 */
export function generateResourcePoolCode(
  className: string,
  featureId: string,
  entry: WritePlanEntry
): string {
  const params = (entry.parameters || {}) as ResourcePoolParams;
  const resourceId = toResourceIdentifier(params.resourceId, "mana");
  const defaultMax = toPositiveNumber(params.maxValue, 100);
  const initialValue = Math.min(toNonNegativeNumber(params.initial, defaultMax), defaultMax);
  const regenRate = parseSupportedRegen(params.regen);

  return `/**
 * ${className}
 * 资源池（server-local numeric pool）- Generated by Rune Weaver
 *
 * Current admitted slice:
 * - maintains only server-local pool state
 * - does not promise runtime UI sync
 * - does not promise auto-regen behavior
 *
 * Config:
 * - featureId: "${featureId}"
 * - resourceId: "${resourceId}"
 * - maxValue: ${defaultMax}
 * - initialValue: ${initialValue}
 * - regenRate: ${regenRate}
 */

interface ResourceState {
  current: number;
  max: number;
}

export class ${className} {
  private static instance: ${className};
  private playerResources: Map<number, ResourceState> = new Map();
  private readonly resourceId: string = "${resourceId}";
  private readonly defaultMax: number = ${defaultMax};
  private readonly initialValue: number = ${initialValue};

  static getInstance(): ${className} {
    if (!${className}.instance) {
      ${className}.instance = new ${className}();
    }
    return ${className}.instance;
  }

  /**
   * 初始化玩家资源
   */
  initPlayer(playerId: number, maxValue?: number): void {
    const resolvedMax = maxValue || this.defaultMax;
    this.playerResources.set(playerId, {
      current: math.min(this.initialValue, resolvedMax),
      max: resolvedMax,
    });
    print(\`[Rune Weaver] Initialized \${this.resourceId} resource for player \${playerId}\`);
  }

  supportsResource(resourceType: string): boolean {
    return resourceType === this.resourceId;
  }

  getResourceId(): string {
    return this.resourceId;
  }

  /**
   * 检查是否有足够资源
   */
  hasEnough(playerId: number, amount: number): boolean {
    const res = this.playerResources.get(playerId);
    if (!res) return false;
    return res.current >= amount;
  }

  /**
   * 消耗资源
   */
  consume(playerId: number, amount: number): boolean {
    if (!this.hasEnough(playerId, amount)) return false;
    
    const res = this.playerResources.get(playerId)!;
    res.current -= amount;
    return true;
  }

  /**
   * 恢复资源
   */
  restore(playerId: number, amount: number): void {
    const res = this.playerResources.get(playerId);
    if (!res) return;
    
    res.current = math.min(res.current + amount, res.max);
  }

  /**
   * 获取当前值
   */
  getCurrent(playerId: number): number {
    return this.playerResources.get(playerId)?.current || 0;
  }

  /**
   * 获取最大值
   */
  getMax(playerId: number): number {
    return this.playerResources.get(playerId)?.max || 0;
  }

}

/**
 * 注册函数 - 当前 slice 只负责本地资源池初始化
 */
export function register${className}(): void {
  const pool = ${className}.getInstance();
  print("[Rune Weaver] ${className} registered for ${resourceId}");
  
  // 监听玩家连接事件 - 使用 GameRules 和自定义事件
  ListenToGameEvent("player_connect_full", (event: any) => {
    const playerId = event.PlayerID;
    if (playerId !== undefined) {
      pool.initPlayer(playerId);
    }
  }, undefined);
}
`;
}
