/**
 * Weighted Pool Generator - Session State Support
 *
 * Supports:
 * - poolStateTracking="session" for selection-pool session state
 * - remainingObjectIds / ownedObjectIds / currentChoiceIds ownership inside data.weighted_pool
 * - deterministic weighted draw without talent-specific tier heuristics
 */

import { WritePlanEntry } from "../../assembler/index.js";

// Dota2 gap-fill boundary anchors.
export const WEIGHTED_POOL_GAP_FILL_BOUNDARIES = {
  selectionPolicy: {
    id: "weighted_pool.selection_policy",
    allowed: ["draw_policy_details", "duplicate_handling", "session_filtering"],
    forbidden: ["pool_contract_changes", "host_routing_changes", "undeclared_persistence"],
  },
} as const;

export interface WeightedPoolParams {
  entries: Array<{ id: string; label: string; description: string; weight: number; tier?: string }>;
  weights?: Record<string, number>;
  tiers?: string[];
  choiceCount?: number;
  drawMode?: "single" | "multiple_without_replacement" | "multiple_with_replacement";
  duplicatePolicy?: "allow" | "avoid_when_possible" | "forbid";
  poolStateTracking?: "none" | "session";
}

function normalizeChoiceCount(value: unknown): number {
  const numeric = Number(value);
  if (!Number.isFinite(numeric) || numeric < 1) {
    return 1;
  }
  return Math.max(1, Math.floor(numeric));
}

/**
 * Generate weighted pool code with session state support.
 */
export function generateWeightedPoolCode(
  className: string,
  featureId: string,
  entry: WritePlanEntry
): string {
  const params = entry.parameters as WeightedPoolParams | undefined;
  const entries = params?.entries;
  const choiceCount = normalizeChoiceCount(params?.choiceCount);
  const drawMode = params?.drawMode || "single";
  const duplicatePolicy = params?.duplicatePolicy || "allow";
  const poolStateTracking = params?.poolStateTracking || "none";

  const entriesCode = entries && entries.length > 0
    ? entries
        .map(
          (item) =>
            `    { id: "${item.id}", label: "${item.label}", description: "${item.description}", weight: ${item.weight}, tier: "${item.tier || "R"}" }`,
        )
        .join(",\n")
    : "    // TODO: Add selection-pool entries";

  const hasSessionState = poolStateTracking === "session";

  const sessionStateDeclaration = hasSessionState
    ? `
  private sessionState: {
    remainingObjectIds: string[];
    ownedObjectIds: string[];
    currentChoiceIds: string[];
  } = {
    remainingObjectIds: [],
    ownedObjectIds: [],
    currentChoiceIds: [],
  };
`
    : "";

  const sessionStateInit = hasSessionState
    ? `
    this.sessionState.remainingObjectIds = initialEntries.map((item) => item.id);
    this.sessionState.ownedObjectIds = [];
    this.sessionState.currentChoiceIds = [];
`
    : "";

  const sessionMethods = hasSessionState
    ? `
  commitSelection(selectedId: string, options?: { trackOwned?: boolean }): void {
    const remainingIndex = this.sessionState.remainingObjectIds.indexOf(selectedId);
    if (remainingIndex > -1) {
      this.sessionState.remainingObjectIds.splice(remainingIndex, 1);
    }

    if (options?.trackOwned !== false && !this.sessionState.ownedObjectIds.includes(selectedId)) {
      this.sessionState.ownedObjectIds.push(selectedId);
    }

    this.sessionState.currentChoiceIds = [];

    print(
      \`[Rune Weaver] ${className}: committed selection \${selectedId}, remaining=\${this.sessionState.remainingObjectIds.length}\`
    );
  }

  getRemainingObjectIds(): string[] {
    return [...this.sessionState.remainingObjectIds];
  }

  getOwnedObjectIds(): string[] {
    return [...this.sessionState.ownedObjectIds];
  }

  getCurrentChoiceIds(): string[] {
    return [...this.sessionState.currentChoiceIds];
  }

  resetSessionState(): void {
    this.sessionState.remainingObjectIds = this.items.map((item) => (item.item as any).id);
    this.sessionState.ownedObjectIds = [];
    this.sessionState.currentChoiceIds = [];
    print(\`[Rune Weaver] ${className}: session state reset\`);
  }
`
    : "";

  return `/**
 * ${className}
 * 加权随机池 - Generated by Rune Weaver
 *
 * Features:
 * - drawMode: ${drawMode}
 * - duplicatePolicy: ${duplicatePolicy}
 * - poolStateTracking: ${poolStateTracking}
 */

interface SelectionPoolEntry {
  id: string;
  label: string;
  description: string;
  weight: number;
  tier?: string;
}

interface WeightedItem<T> {
  item: T;
  weight: number;
  tier?: number;
}

export class ${className}<T extends SelectionPoolEntry = SelectionPoolEntry> {
  private static instance?: ${className}<any>;
  private items: WeightedItem<T>[] = [];
  private totalWeight: number = 0;
${sessionStateDeclaration}
  static getInstance<U extends SelectionPoolEntry = SelectionPoolEntry>(): ${className}<U> {
    if (!${className}.instance) {
      ${className}.instance = new ${className}<U>();
    }
    return ${className}.instance as ${className}<U>;
  }

  constructor() {
${entries ? `    const initialEntries = [
${entriesCode}
    ] as T[];
    for (const entry of initialEntries) {
      this.add(entry, entry.weight, entry.tier ? this.tierToNumber(entry.tier) : 0);
    }${sessionStateInit}` : `    ${entriesCode}`}
  }

  private tierToNumber(tier: string): number {
    const tierMap: Record<string, number> = { R: 1, SR: 2, SSR: 4, UR: 7 };
    return tierMap[tier] || 1;
  }

  private pickWeightedItem(candidates: WeightedItem<T>[]): WeightedItem<T> | null {
    if (candidates.length === 0) {
      return null;
    }

    const totalWeight = candidates.reduce((sum, candidate) => sum + candidate.weight, 0);
    if (totalWeight <= 0) {
      return null;
    }

    let random = RandomFloat(0, totalWeight);
    for (const candidate of candidates) {
      random -= candidate.weight;
      if (random <= 0) {
        return candidate;
      }
    }

    return candidates[candidates.length - 1] || null;
  }

  private getAvailableItems(): WeightedItem<T>[] {
${hasSessionState
    ? `    return this.items.filter((candidate) =>
      this.sessionState.remainingObjectIds.includes((candidate.item as any).id)
    );`
    : "    return [...this.items];"}
  }

  add(item: T, weight: number, tier?: number): void {
    this.items.push({ item, weight, tier });
    this.totalWeight += weight;
  }

  remove(item: T): boolean {
    const index = this.items.findIndex((candidate) => candidate.item === item);
    if (index === -1) {
      return false;
    }

    this.totalWeight -= this.items[index].weight;
    this.items.splice(index, 1);
    return true;
  }

  clear(): void {
    this.items = [];
    this.totalWeight = 0;
${hasSessionState ? `    this.sessionState.remainingObjectIds = [];
    this.sessionState.ownedObjectIds = [];
    this.sessionState.currentChoiceIds = [];
` : ""}  }

  draw(): T | null {
    const drawn = this.pickWeightedItem(this.items);
    return drawn ? drawn.item : null;
  }

  drawMultiple(count: number): T[] {
    const requestedCount = Math.max(1, Math.floor(count));
    const result: T[] = [];
    const workingItems = [...this.items];

    while (result.length < requestedCount && workingItems.length > 0) {
      const drawn = this.pickWeightedItem(workingItems);
      if (!drawn) {
        break;
      }

      result.push(drawn.item);
      const index = workingItems.indexOf(drawn);
      if (index >= 0) {
        workingItems.splice(index, 1);
      }
    }

    return result;
  }

  /**
   * GAP_FILL_BOUNDARY: weighted_pool.selection_policy
   * Allowed: weighted draw policy details, duplicate handling, session-aware filtering.
   * Forbidden: pool contract changes, host routing changes, undeclared persistence semantics.
   */
  drawForSelection(count: number = ${choiceCount}): T[] {
    const requestedCount = Math.max(1, Math.floor(count));
    const result: T[] = [];
    const configuredDrawMode: string = "${drawMode}";
    const configuredDuplicatePolicy: string = "${duplicatePolicy}";
    const allowReplacement =
      configuredDrawMode === "multiple_with_replacement" && configuredDuplicatePolicy === "allow";
    const workingItems = this.getAvailableItems();

    if (workingItems.length === 0) {
      print(\`[Rune Weaver] ${className}: no available items in pool\`);
      return [];
    }

    while (result.length < requestedCount && workingItems.length > 0) {
      const drawn = this.pickWeightedItem(workingItems);
      if (!drawn) {
        break;
      }

      result.push(drawn.item);

      if (configuredDrawMode === "single") {
        break;
      }

      if (!allowReplacement) {
        const drawnId = (drawn.item as any).id;
        for (let index = workingItems.length - 1; index >= 0; index -= 1) {
          if ((workingItems[index].item as any).id === drawnId) {
            workingItems.splice(index, 1);
          }
        }
      }
    }
${hasSessionState ? `
    this.sessionState.currentChoiceIds = result.map((item) => (item as any).id);
` : ""}
    return result;
  }
${sessionMethods}
  drawByTier(tier: number): T | null {
    const tierItems = this.items.filter((candidate) => candidate.tier === tier);
    const drawn = this.pickWeightedItem(tierItems);
    return drawn ? drawn.item : null;
  }

  getAllItems(): WeightedItem<T>[] {
    return [...this.items];
  }

  getCount(): number {
    return this.items.length;
  }
}

export function register${className}(): void {
  ${className}.getInstance();
  print("[Rune Weaver] ${className} registered");
}
`;
}
