/**
 * Dota2 Adapter - Host Write Executor
 * 
 * 将 WritePlan 转换为实际的文件写入操作
 * T034: 实现 Write Plan -> Host Write Executor
 */

import { existsSync, mkdirSync, writeFileSync, readFileSync } from "fs";
import { dirname, join } from "path";
import { WritePlan, WritePlanEntry } from "../assembler/index.js";
import {
  RuneWeaverWorkspace,
  readWorkspace,
  writeWorkspace,
  addFeatureToWorkspace,
} from "../../../core/workspace/index.js";
import { generateCode } from "../generator/index.js";

/**
 * 执行结果
 */
export interface WritePlanExecutionResult {
  /** 是否成功 */
  success: boolean;
  /** 写入的文件数 */
  filesWritten: number;
  /** 跳过的文件数（已存在且内容相同） */
  filesSkipped: number;
  /** 失败的文件数 */
  filesFailed: number;
  /** 错误列表 */
  errors: string[];
  /** 成功写入的文件路径 */
  writtenFiles: string[];
  /** 更新的 workspace */
  workspace?: RuneWeaverWorkspace;
}

/**
 * 执行选项
 */
export interface ExecutionOptions {
  /** 项目根路径 */
  projectPath: string;
  /** Feature ID */
  featureId: string;
  /** Intent 类型 */
  intentKind: string;
  /** Blueprint ID */
  blueprintId: string;
  /** 是否dry-run */
  dryRun?: boolean;
  /** 是否强制覆盖 */
  force?: boolean;
}

/**
 * 文件头标记模板
 */
const FILE_HEADER_TEMPLATE = `// Generated by Rune Weaver
// featureId: {featureId}
// revision: {revision}
// blueprintId: {blueprintId}
// generatedAt: {timestamp}

`;

/**
 * 生成文件头
 */
function generateFileHeader(
  featureId: string,
  revision: number,
  blueprintId: string
): string {
  return FILE_HEADER_TEMPLATE
    .replace("{featureId}", featureId)
    .replace("{revision}", String(revision))
    .replace("{blueprintId}", blueprintId)
    .replace("{timestamp}", new Date().toISOString());
}

/**
 * 确保目录存在
 */
function ensureDirectoryExists(filePath: string): void {
  const dir = dirname(filePath);
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }
}

/**
 * 检查文件内容是否相同（用于幂等性）
 */
function isContentSame(filePath: string, newContent: string): boolean {
  if (!existsSync(filePath)) {
    return false;
  }
  try {
    const existingContent = readFileSync(filePath, "utf-8");
    return existingContent === newContent;
  } catch {
    return false;
  }
}

/**
 * 写入单个文件
 */
function writeEntry(
  entry: WritePlanEntry,
  projectPath: string,
  featureId: string,
  blueprintId: string,
  force: boolean
): { success: boolean; skipped: boolean; error?: string } {
  const fullPath = join(projectPath, entry.targetPath);

  // 生成真实可执行代码（T034 修复）
  const generated = generateCode(entry, featureId);
  
  // 添加文件头
  const header = generateFileHeader(featureId, 1, blueprintId);
  const contentWithHeader = header + generated.content;

  // 检查是否需要跳过（幂等性）
  if (!force && isContentSame(fullPath, contentWithHeader)) {
    return { success: true, skipped: true };
  }

  try {
    // 确保目录存在
    ensureDirectoryExists(fullPath);

    // 写入文件 - 现在写入的是真实可执行代码
    writeFileSync(fullPath, contentWithHeader, "utf-8");

    return { success: true, skipped: false };
  } catch (error) {
    return {
      success: false,
      skipped: false,
      error: `写入失败 ${entry.targetPath}: ${
        error instanceof Error ? error.message : String(error)
      }`,
    };
  }
}

/**
 * 应用 Write Plan
 * 
 * 将 WritePlan 转换为实际的文件写入操作
 */
export async function applyWritePlan(
  plan: WritePlan,
  options: ExecutionOptions
): Promise<WritePlanExecutionResult> {
  const result: WritePlanExecutionResult = {
    success: false,
    filesWritten: 0,
    filesSkipped: 0,
    filesFailed: 0,
    errors: [],
    writtenFiles: [],
  };

  // 1. 读取当前 workspace
  const { workspace, error: readError } = readWorkspace(options.projectPath);
  if (!workspace) {
    result.errors.push(`无法读取 workspace: ${readError}`);
    return result;
  }

  // 2. 检查 workspace 是否已初始化
  if (workspace.hostType !== "dota2-x-template") {
    result.errors.push(`不支持的宿主类型: ${workspace.hostType}`);
    return result;
  }

  // 3. 验证 Write Plan 路径
  for (const entry of plan.entries) {
    const isInNamespace =
      entry.targetPath.includes("rune_weaver") ||
      entry.targetPath.startsWith("game/scripts/npc/");
    if (!isInNamespace) {
      result.errors.push(`路径不在受控命名空间内: ${entry.targetPath}`);
      return result;
    }
  }

  // 4. dry-run 模式
  if (options.dryRun) {
    console.log("[DRY-RUN] 将要写入以下文件:");
    for (const entry of plan.entries) {
      console.log(`  - ${entry.targetPath}`);
    }
    result.success = true;
    return result;
  }

  // 5. 执行写入
  const writtenFiles: string[] = [];

  for (const entry of plan.entries) {
    const writeResult = writeEntry(
      entry,
      options.projectPath,
      options.featureId,
      options.blueprintId,
      options.force || false
    );

    if (writeResult.success) {
      if (writeResult.skipped) {
        result.filesSkipped++;
      } else {
        result.filesWritten++;
        writtenFiles.push(entry.targetPath);
      }
    } else {
      result.filesFailed++;
      if (writeResult.error) {
        result.errors.push(writeResult.error);
      }
    }
  }

  result.writtenFiles = writtenFiles;

  // 6. 更新 workspace
  if (writtenFiles.length > 0) {
    const updatedWorkspace = addFeatureToWorkspace(workspace, {
      featureId: options.featureId,
      intentKind: options.intentKind,
      status: "active",
      blueprintId: options.blueprintId,
      generatedFiles: writtenFiles,
      entryBindings: writtenFiles.map((file) => ({
        target: file.includes("panorama") ? "ui" : "server",
        file,
        kind: "import",
      })),
    });

    // 写入更新后的 workspace
    const writeResult = writeWorkspace(options.projectPath, updatedWorkspace);
    if (!writeResult.success) {
      result.errors.push(`更新 workspace 失败: ${writeResult.error}`);
    } else {
      result.workspace = updatedWorkspace;
    }
  }

  result.success = result.filesFailed === 0;
  return result;
}

/**
 * 打印执行结果
 */
export function printExecutionResult(result: WritePlanExecutionResult): void {
  console.log("=".repeat(60));
  console.log("Write Plan 执行结果");
  console.log("=".repeat(60));
  console.log();

  console.log(`状态: ${result.success ? "✅ 成功" : "❌ 失败"}`);
  console.log(`写入文件: ${result.filesWritten}`);
  console.log(`跳过文件: ${result.filesSkipped}`);
  console.log(`失败文件: ${result.filesFailed}`);
  console.log();

  if (result.writtenFiles.length > 0) {
    console.log("写入的文件:");
    for (const file of result.writtenFiles) {
      console.log(`  ✅ ${file}`);
    }
    console.log();
  }

  if (result.errors.length > 0) {
    console.log("错误:");
    for (const error of result.errors) {
      console.log(`  ❌ ${error}`);
    }
    console.log();
  }

  console.log("=".repeat(60));
}

/**
 * 验证是否可以执行写入
 */
export function canExecuteWritePlan(
  projectPath: string
): { canExecute: boolean; error?: string } {
  // 1. 检查 workspace 是否存在
  const { workspace, error } = readWorkspace(projectPath);
  if (!workspace) {
    return {
      canExecute: false,
      error: `宿主未初始化: ${error}. 请先运行: npm run cli -- dota2 init --host ${projectPath}`,
    };
  }

  // 2. 检查宿主类型
  if (workspace.hostType !== "dota2-x-template") {
    return {
      canExecute: false,
      error: `不支持的宿主类型: ${workspace.hostType}`,
    };
  }

  // 3. 检查命名空间目录是否存在
  const serverNsPath = join(
    projectPath,
    "game/scripts/src/rune_weaver"
  );
  const panoramaNsPath = join(
    projectPath,
    "content/panorama/src/rune_weaver"
  );

  if (!existsSync(serverNsPath) && !existsSync(panoramaNsPath)) {
    return {
      canExecute: false,
      error: "命名空间目录不存在，宿主可能未正确初始化",
    };
  }

  return { canExecute: true };
}
