/**
 * Legacy Executor - 兼容层
 *
 * 仅用于旧代码过渡，新代码请使用 write-executor.ts 中的 Phase 1 API。
 *
 * 此文件将在未来版本中移除。
 *
 * @deprecated Use executeWritePlan from write-executor.ts instead
 */

import { existsSync, mkdirSync, writeFileSync, readFileSync } from "fs";
import { dirname, join } from "path";
import { WritePlan as LegacyWritePlan, WritePlanEntry } from "../assembler/index.js";
import {
  RuneWeaverWorkspace,
  readWorkspace,
  writeWorkspace,
  addFeatureToWorkspace,
} from "../../../core/workspace/index.js";
import { generateCode } from "../generator/index.js";

/**
 * 执行结果 (Legacy)
 * @deprecated Use WriteResult from write-executor.ts instead
 */
export interface WritePlanExecutionResult {
  success: boolean;
  filesWritten: number;
  filesSkipped: number;
  filesFailed: number;
  errors: string[];
  writtenFiles: string[];
  workspace?: RuneWeaverWorkspace;
}

/**
 * 执行选项 (Legacy)
 * @deprecated Use WriteExecutorOptions from write-executor.ts instead
 */
export interface ExecutionOptions {
  projectPath: string;
  featureId: string;
  intentKind: string;
  blueprintId: string;
  dryRun?: boolean;
  force?: boolean;
}

const FILE_HEADER_TEMPLATE = `// Generated by Rune Weaver
// featureId: {featureId}
// revision: {revision}
// blueprintId: {blueprintId}
// generatedAt: {timestamp}

`;

function generateFileHeader(
  featureId: string,
  revision: number,
  blueprintId: string
): string {
  return FILE_HEADER_TEMPLATE
    .replace("{featureId}", featureId)
    .replace("{revision}", String(revision))
    .replace("{blueprintId}", blueprintId)
    .replace("{timestamp}", new Date().toISOString());
}

function ensureDirectoryExists(filePath: string): void {
  const dir = dirname(filePath);
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }
}

function isContentSame(filePath: string, newContent: string): boolean {
  if (!existsSync(filePath)) {
    return false;
  }
  try {
    const existingContent = readFileSync(filePath, "utf-8");
    return existingContent === newContent;
  } catch {
    return false;
  }
}

function writeEntry(
  entry: WritePlanEntry,
  projectPath: string,
  featureId: string,
  blueprintId: string,
  force: boolean
): { success: boolean; skipped: boolean; error?: string } {
  const fullPath = join(projectPath, entry.targetPath);

  const generated = generateCode(entry, featureId);
  
  const header = generateFileHeader(featureId, 1, blueprintId);
  const contentWithHeader = header + generated.content;

  if (!force && isContentSame(fullPath, contentWithHeader)) {
    return { success: true, skipped: true };
  }

  try {
    ensureDirectoryExists(fullPath);
    writeFileSync(fullPath, contentWithHeader, "utf-8");
    return { success: true, skipped: false };
  } catch (error) {
    return {
      success: false,
      skipped: false,
      error: `写入失败 ${entry.targetPath}: ${
        error instanceof Error ? error.message : String(error)
      }`,
    };
  }
}

/**
 * 应用 Write Plan (Legacy)
 * @deprecated Use executeWritePlan from write-executor.ts instead
 */
export async function applyWritePlan(
  plan: LegacyWritePlan,
  options: ExecutionOptions
): Promise<WritePlanExecutionResult> {
  const result: WritePlanExecutionResult = {
    success: false,
    filesWritten: 0,
    filesSkipped: 0,
    filesFailed: 0,
    errors: [],
    writtenFiles: [],
  };

  const { workspace, error: readError } = readWorkspace(options.projectPath);
  if (!workspace) {
    result.errors.push(`无法读取 workspace: ${readError}`);
    return result;
  }

  if (workspace.hostType !== "dota2-x-template") {
    result.errors.push(`不支持的宿主类型: ${workspace.hostType}`);
    return result;
  }

  for (const entry of plan.entries) {
    const isInNamespace =
      entry.targetPath.includes("rune_weaver") ||
      entry.targetPath.startsWith("game/scripts/npc/");
    if (!isInNamespace) {
      result.errors.push(`路径不在受控命名空间内: ${entry.targetPath}`);
      return result;
    }
  }

  if (options.dryRun) {
    console.log("[DRY-RUN] 将要写入以下文件:");
    for (const entry of plan.entries) {
      console.log(`  - ${entry.targetPath}`);
    }
    result.success = true;
    return result;
  }

  const writtenFiles: string[] = [];

  for (const entry of plan.entries) {
    const writeResult = writeEntry(
      entry,
      options.projectPath,
      options.featureId,
      options.blueprintId,
      options.force || false
    );

    if (writeResult.success) {
      if (writeResult.skipped) {
        result.filesSkipped++;
      } else {
        result.filesWritten++;
        writtenFiles.push(entry.targetPath);
      }
    } else {
      result.filesFailed++;
      if (writeResult.error) {
        result.errors.push(writeResult.error);
      }
    }
  }

  result.writtenFiles = writtenFiles;

  if (writtenFiles.length > 0) {
    const updatedWorkspace = addFeatureToWorkspace(workspace, {
      featureId: options.featureId,
      intentKind: options.intentKind,
      status: "active",
      blueprintId: options.blueprintId,
      generatedFiles: writtenFiles,
      entryBindings: writtenFiles.map((file) => ({
        target: file.includes("panorama") ? "ui" : "server",
        file,
        kind: "import",
      })),
    });

    const writeResult = writeWorkspace(options.projectPath, updatedWorkspace);
    if (!writeResult.success) {
      result.errors.push(`更新 workspace 失败: ${writeResult.error}`);
    } else {
      result.workspace = updatedWorkspace;
    }
  }

  result.success = result.filesFailed === 0;
  return result;
}

/**
 * 打印执行结果 (Legacy)
 * @deprecated
 */
export function printExecutionResult(result: WritePlanExecutionResult): void {
  console.log("=".repeat(60));
  console.log("Write Plan 执行结果");
  console.log("=".repeat(60));
  console.log();

  console.log(`状态: ${result.success ? "✅ 成功" : "❌ 失败"}`);
  console.log(`写入文件: ${result.filesWritten}`);
  console.log(`跳过文件: ${result.filesSkipped}`);
  console.log(`失败文件: ${result.filesFailed}`);
  console.log();

  if (result.writtenFiles.length > 0) {
    console.log("写入的文件:");
    for (const file of result.writtenFiles) {
      console.log(`  ✅ ${file}`);
    }
    console.log();
  }

  if (result.errors.length > 0) {
    console.log("错误:");
    for (const error of result.errors) {
      console.log(`  ❌ ${error}`);
    }
    console.log();
  }

  console.log("=".repeat(60));
}

/**
 * 验证是否可以执行写入 (Legacy)
 * @deprecated
 */
export function canExecuteWritePlan(
  projectPath: string
): { canExecute: boolean; error?: string } {
  const { workspace, error } = readWorkspace(projectPath);
  if (!workspace) {
    return {
      canExecute: false,
      error: `宿主未初始化: ${error}. 请先运行: npm run cli -- dota2 init --host ${projectPath}`,
    };
  }

  if (workspace.hostType !== "dota2-x-template") {
    return {
      canExecute: false,
      error: `不支持的宿主类型: ${workspace.hostType}`,
    };
  }

  const serverNsPath = join(projectPath, "game/scripts/src/rune_weaver");
  const panoramaNsPath = join(projectPath, "content/panorama/src/rune_weaver");

  if (!existsSync(serverNsPath) && !existsSync(panoramaNsPath)) {
    return {
      canExecute: false,
      error: "命名空间目录不存在，宿主可能未正确初始化",
    };
  }

  return { canExecute: true };
}
