/**
 * Refresh UI Index
 * 
 * Generates the main index.tsx that aggregates all UI features
 */

import { UIIndexGenerationOptions, GeneratedUIIndex } from "./types.js";
import { toPascalCase } from "./utils/template-engine.js";

/**
 * Generate UI index file content
 */
export function generateUIIndex(options: UIIndexGenerationOptions): GeneratedUIIndex {
  const { features } = options;
  
  // Generate imports
  const imports = features.map(f => {
    const componentName = toPascalCase(f.featureId);
    return `import { ${componentName} } from "./${f.featureId}";`;
  }).join("\n");
  
  // Generate component renders
  const componentRenders = features.map(f => {
    const componentName = toPascalCase(f.featureId);
    return `      <${componentName} />`;
  }).join("\n");
  
  // Generate exports for individual components
  const exports = features.map(f => {
    const componentName = toPascalCase(f.featureId);
    return `export { ${componentName} } from "./${f.featureId}";`;
  }).join("\n");
  
  const content = `// Generated by Rune Weaver
// UI Index - Auto refreshed
// Features: ${features.map(f => f.featureId).join(", ")}

import React from "react";
${imports}

export function RuneWeaverGeneratedUIRoot(): React.ReactElement {
  return (
    <>
${componentRenders}
    </>
  );
}

// Individual component exports
${exports}
`;
  
  return {
    fileName: "index.tsx",
    content,
  };
}

/**
 * Generate index for single feature (simple case)
 */
export function generateSingleFeatureIndex(featureId: string): GeneratedUIIndex {
  return generateUIIndex({
    features: [{ featureId, componentName: toPascalCase(featureId) }],
  });
}

/**
 * Generate index for common combinations
 */
export function generateComboIndex(featureIds: string[]): GeneratedUIIndex {
  return generateUIIndex({
    features: featureIds.map(id => ({
      featureId: id,
      componentName: toPascalCase(id),
    })),
  });
}
